### ISSUE TITLE
Global npm packages are installed inside specific node folder

### ISSUE THREAD

**Issue by lttr** [webinstall/webi-installers#144]
## What were you trying to install (or what else went wrong)?

I am installing nodejs.

## What exactly did you do?

I have installed one version initially and now a different version. Before installing the second one I have installed several global npm packages.

## What went wrong?

I would expect global npm packages would still work. However they are installed inside the specific nodejs installation folder. They are no longer globally executable.

Before using webi, I have been setting `npm config set prefix` to some unchanging path like `~/.npm-global`. Now the `npm config get prefix` gives me different path before and after a nodejs installation.

## Which OS did you try on?

- [ ] Mac
- [ ] Windows
- [x] Linux

**Comment by coolaj86** [comment]
This is actually not a bug. This is the expected (and desired) behavior.

One of the key points of webi is consistency.

Because each install of node is sectioned off, you'll never get weird module compatibility errors when switching between versions (i.e. `webi node@12`, `webi node@14`).

The trade off, however, is that you will need to reinstall your global npms when switching versions.

**Comment by coolaj86** [comment]
If you have a lot of globally installed programs, I'd recommend switching back to the prior version (`ls -d ~/.local/opt/node*`) and then getting the list via `npm list -g --depth 0`.

For example:

```bash
npm list -g --depth 0 | tail -n +2 | cut -d' ' -f 2
```

```txt
npm@6.14.8
prettier@2.1.2
```

**Comment by lttr** [comment]
Thank you for great explanation. I'm using webi for convenience, but the point with consistency is probably more important.
