### ISSUE TITLE
[Question] How to fix libssl dylib errors?

### ISSUE THREAD

**Issue by rodbv** [webinstall/webi-installers#145]
## What were you trying to install (or what else went wrong)?

Webi

## What exactly did you do?

Ran `curl -sS https://webinstall.dev/webi | bash`

## What went wrong?

Got the following error:

```

Thanks for using webi to install 'webi' on 'macos/amd64'.
Have a problem? Experience a bug? Please let us know:
        https://github.com/webinstall/packages/issues

dyld: Library not loaded: /usr/local/opt/openssl/lib/libssl.1.0.0.dylib
  Referenced from: /usr/local/bin/wget
  Reason: image not found
pathman-bootstrap.sh: line 123: 61805 Abort trap: 6           wget -q --show-progress --user-agent="wget $WEBI_UA" -c "$my_url" -O "$my_dl.part"
failed to download from https://git.rootprojects.org/attachments/40d6ce14-e340-4f66-a01d-163b814437c2
```

## Which OS did you try on?

- [x] Mac
- [ ] Windows
- [ ] Linux

## What type of computer (i.e. laptop, desktop, Raspberry Pi)?

- [x] Laptop or Desktop (amd64 / x86-64)
- [ ] Raspberry Pi (ARM-64)
- [ ] Other (please specify, if you know)

**Comment by coolaj86** [comment]
I'm guessing that you have `brew` installed and it had been 6 months since the last time you did a `brew update` and then you finally did, and then it screwed up everything that uses the network? Would that be correct?

The simplest solution: `sudo rm /usr/local/bin/wget` and try again.

The real solution: You probably need to [uninstall brew](https://github.com/homebrew/install#uninstall-homebrew) and reinstall it again. I'd recommend installing `brew` with webi as then it will isolate it away from system-level files in `~/.local/opt/brew`.

**Comment by coolaj86** [comment]
(and if it wasn't brew, something else you've installed has messed up `libssl`)

**Comment by ryanburnette** [comment]
Which version of macOS?

`brew update` and/or `brew doctor`  might help, might also need to run `brew upgrade openssl`

**Comment by rodbv** [comment]
Thanks for the quick response @coolaj86 and @ryanburnette! You are right it was a brew issue and uninstalling it/reinstalling it via webi worked!

**Comment by coolaj86** [comment]
Fair warning: Webi-installed brew will take longer compile times for certain programs (due to the linker needing to use fresh builds from `~/.local/opt/` rather than pre-built from the casks, etc).

If there are any tools that you use that have big dependency lists or long compile times - such as `ffmpeg`, `mingw`, or `musl-cross`, I'd recommend going ahead and letting those compile while you sleep tonight.
