### ISSUE TITLE
Request for kubectl

### ISSUE THREAD

**Issue by mouadmem16** [webinstall/webi-installers#250]
The kubernetes command line tool, kubectl, allows you to run commands in Kubernetes clusters. You can use kubectl to deploy applications, inspect and manage cluster resources, and view logs. For a complete list of kubectl operations 
https://kubernetes.io/fr/docs/tasks/tools/install-kubectl/

**Comment by coolaj86** [comment]
Hmmm... I'm probably not the right person to take this on since I'm not using kubectl, but I did a little digging and perhaps someone else can confirm if these are the correct release API urls and such:

- Latest version: https://storage.googleapis.com/kubernetes-release/release/stable.txt
- All platforms?? https://storage.googleapis.com/kubernetes-release/
- Download??? `archive/anago-v1.10.0-alpha.1/k8s.io/kubernetes/_output-v1.10.0-alpha.1/dockerized/bin/darwin/amd64/kubectl` (what's the root of the url? what's "anago"?)
    - https://storage.googleapis.com/kubernetes-release/release/{{VERSION}}/bin/linux/amd64/kubectl
    - https://storage.googleapis.com/kubernetes-release/release/v1.21.1/bin/linux/amd64/kubectl
    - https://storage.googleapis.com/kubernetes-release/release/v1.21.1/bin/darwin/amd64/kubectl
    - https://storage.googleapis.com/kubernetes-release/release/v1.21.1/bin/windows/amd64/kubectl.exe

Where can we get a list of versions?

**Comment by coolaj86** [comment]
Tagging this as a "someday".

I'm willing to work with someone else on this and would accept a PR.
