### ISSUE TITLE
[Bug] `z` (zoxide) should put `z` in PATH

### ISSUE THREAD

**Issue by coolaj86** [webinstall/webi-installers#255]
One of the core tenants of `webi` is that when stuff installs, it should Just Work™.

zoxide should follow the same "reasonable defaults" pattern.

I get that some people may want to customize their setup, but if they feel that webi's sane defaults are too intrusive to be a good starting point, maybe webi isn't for them.

At the least bash, zsh, and fish (what I view as "the common shells" should be supported out-of-the-box).
- People only use bash because either A) they don't know what they're doing in the first place or B) it's the most convenient option on an ephemeral device.
- People who use fish  expect things to just work out of the box. That's the slogan, more or less.
- zsh is the new bash (default on macos), but worth using as a day-to-day shell.

Re: https://github.com/webinstall/webi-installers/pull/223#issuecomment-861208448

cc/ @ajeetdsouza

**Comment by ajeetdsouza** [comment]
Reiterating what I said on the other thread, I would _never_ use a utility that just edits my config files for the sake of "sane defaults" -- they're _config_ files because _I configure them_.

- It's _extremely_ intrusive. In fact, I don't know of a single other utility that inserts itself into a user's `.bashrc` or equivalent. Even shell plugin managers give you a couple of lines to copy-paste into your config files.
- My dotfiles are carefully formatted and version-controlled. They're personal, and I would absolutely hate it if a script that messed with my setup.
- There are so many scenarios that aren't being considered here:
  - A user might be using multiple shells and only wants zoxide on only one of them.
  - A user might want zoxide installed with `--cmd j` or some other option set.
  - Some users don't use `zoxide init` at all -- they write their own `cd` command built on top of zoxide.
  - My `.zshrc` file sources a few other files. One of those files initializes zoxide. Adding `zoxide init` a second time to my main `.zshrc` file would be redundant.
  - A user might just be evaluating zoxide before making a decision to permanently add it to their config file -- exactly how you first used it in the livestream. I don't think you would have liked it if zoxide initialized itself on all your shells before you even had a chance to see if you liked it.

IMO, if you're looking to "automate" something like this, you should be looking at using a dotfile manager that will share your `.zshrc` across different computers, rather than relying on installers to add themselves to your shell configuration.

If you see how `cargo`'s `curl | bash` script deals with things, it doesn't try to mess with your configuration, but instead provides instructions on how to add `~/.cargo` to your `$PATH`. I think that's the way to go -- we can add a link / instructions so that users can add the one-liner to their shell.

**Comment by coolaj86** [comment]
> It's extremely intrusive.

That's subjective. It's not peaking on you in the shower. It's making things work.

> I don't know of a single other utility that inserts itself into a user's .bashrc or equivalent

Webi itself does this (via `pathman`), and continues to use `pathman` for everything you install that goes into `~/.local/opt/x/bin`. Brew does this. Last time I checked cargo does this as well, but it doesn't do it for all shells equally well.

> My dotfiles are carefully formatted and version-controlled

Then if you don't like what it does you can just `git diff` or similar, right?

> Adding zoxide init a second time to my main .zshrc file would be redundant.

Yes... but then are you even installing it via webi?

> I don't think you would have liked it if zoxide initialized itself on all your shells before you even had a chance to see if you liked it.

Nothing's permanent about it. You just comment it out or delete it.

And yes, I would prefer that when I use a tool it just works without me having to make menial decisions that are necessary, but unimportant. Hence [`vim-essentials`](https://webinstall.dev/vim-essentials).

That said, I also want the documentation to be easy and clear about how and where to uninstall. Anything that can't be undone with `rm -rf ~/.local/bin ~/.local/opt` should be clearly documented.

## Education vs Just Works

Most users don't want to be educated, they just want to reap the benefits.

## Conclusion

I agree with you that for the minority of people who heavily customize their rc scripts that it should be possible for webi to not add the zoxide init a second time.

I disagree that it shouldn't just do it for you.

I would prefer that it say something like

> These files have been edited to initialize `z` each time you start a new terminal or shell:
>   - ~/.bashrc
>   - ~/.config/fish/config.fish

However, since it's your utility, and you're doing the work for it, I also don't expect you to do something that you're morally opposed todoing.

I'm okay with the idea of printing out something like

> Copy and paste this to finish the install for the following shells:
> 
> bash:
>     echo '' >> ~/.bashrc
>     echo '# add "z" and its cache to your shell session' >> .bashrc
>     echo 'zoxide init | source' >> .bashrc
>
> Or, if you'd like to install zoxide for all supported shells:
>     curl https://webinstall.dev/packages/zoxide/init.sh | bash

**Comment by coolaj86** [comment]
> However, since it's your utility, and you're doing the work for it, I also don't expect you to do something that you're morally opposed to doing.
> 
> I'm okay with the idea of printing out something like (see above)

@ajeetdsouza ^^ thoughts?

**Comment by ajeetdsouza** [comment]
Makes sense, I'll create a PR with initialisation instructions soon. I'm still opposed to the "install for all shells" script, though -- I'll put instructions for bash, zsh, and fish, and a link below that for users of other shells.
