### ISSUE TITLE
[Bug] Alpine Linux Support

### ISSUE THREAD

**Issue by elasticdotventures** [webinstall/webi-installers#259]
## What were you trying to install (or what else went wrong)?
```
docker container run -it alpine /bin/sh
```

## What exactly did you do?
```
apk --no-cache add curl bash
curl -sS https://webinstall.dev/webi | bash
```

## What went wrong?

Thanks for using webi to install 'webi@stable' on 'Linux/x86_64'.
Have a problem? Experience a bug? Please let us know:
        https://github.com/webinstall/packages/issues

failed to add "/root/.local/bin" to PATH: "" is not a recognized shell and found none of .bashrc, .zshrc, .config/fish/config.fish
'webi' installed to ~/.local/bin/webi

Usage:
    webi <package-name>[@version] ...

Example:
    webi node@lts prettier vim-essentials

failed to add "/root/.local/bin" to PATH: "" is not a recognized shell and found none of .bashrc, .zshrc, .config/fish/config.fish/ #

## Which OS did you try on?

- [ x] Linux / Alpine (android)

## What type of computer (i.e. laptop, desktop, Raspberry Pi)?

- [ ] Laptop or Desktop (amd64 / x86-64)
- [ ] Raspberry Pi (ARM-64)
- [ ] Other (please specify, if you know)

**Comment by coolaj86** [comment]
> failed to add "/root/.local/bin" to PATH: "" is not a recognized shell and found none of .bashrc, .zshrc, .config/fish/config.fish
'webi' installed to ~/.local/bin/webi

What shell are you using? And what config file do you want to use?

If you intend to use bash, you probably want to `touch .bashrc`.

**Comment by coolaj86** [comment]
I don't think this is actually a bug, but rather that you don't have a config file for your shell.

Since I haven't heard back from you, so I'm going to close this out. Feel free to re-open if I'm wrong.

**Comment by cvoges12** [comment]
@coolaj86 What configuration is required for the shell?

**Comment by coolaj86** [comment]
@cvoges12 Depends on what you mean by "the shell".

For most shells it's just `source ~/.config/envman/PATH.env`.

There are a few things, such as Rust, which may be special, depending on _which_ shell you mean.

**Comment by cvoges12** [comment]
That's interesting because I don't recall any systems that even have a `~/.config/envman/`, and I've used many systems from BSDs to Linux to even macOS. But typically, no extra or special configuration is necessary when shell as a dependency. I don't think I can recall a single time software has asked me to append a line to the shell profile or rc files.

Also, I'm not sure why any special PATH is being enforced in the first place.

On a side note, the only pros I can encourage from switching to bash to one of the many POSIX shell implementations is maybe perf and portability. I know that Almquist shell (the sh used on alpine linux) is often a good bit faster than bash and comes at a much smaller binary size than bash. I've also worked on quite a few embedded systems which never had bash as well but did still had a POSIX compliant shell of some sort. So I think it is fairly subjective to argue for sh or bash and typically ends up in "holy wars".

**Comment by coolaj86** [comment]
`~/.config/envman/PATH.env` is what `pathman` creates and updates - so that there's a machine-readable configuration in a single place, rather than many different bespoke edits to RC files - the idea being the RC files are for users to configure, and not for machines to mess up, and likewise that machines should have a place to update PATH without coming into conflict with a user's custom modifications of their RC files.

Most installers require `root` privileges and install things into paths that are already in the default `PATH`, such as `/usr/local/bin`. However, this leads to permissions conflicts (`brew` and `node` and `go` `.pkg`s all fighting over whether the user or the system should own `/usr/local`) and conflicts with system libraries (such as brew's `libssl` coming in conflict with MacOS's `libssl` when installing gnu `ssh` or gnu `curl`) or different versions of the same program (`node-v12` vs `node-v16`), etc.

Webi is designed for maximum security and reliability, and I'd like it to be as portable as possible too - hence I'm open to transitioning to `sh`, especially if there's an automated way to "downgrade" the bash scripts without causing conflict (such as having to maintain unreliable or deeply nuanced conditions to handle peculiarities between `dash`, `almquist`, `sh`, etc).

**Comment by coolaj86** [comment]
@cvoges12 @elasticdotventures All Webi scripts are now POSIX compliant.

I've opened #505 to pave the path for removing `pathman` in favor of a Posix shell function that only handles the use case of adding something to the `PATH`, and only when strictly needed.
