### ISSUE TITLE
Any curl install command from the website errors because it pulls HTML

### ISSUE THREAD

**Issue by wburningham** [webinstall/webi-installers#276]
## What were you trying to install (or what else went wrong)?

curl https://webinstall.dev/webi | bash

## What exactly did you do?

1. Start with system without any webi installed tools.
2. curl https://webinstall.dev/webi | cat
3. curl -sSL https://webinstall.dev/webi | cat

## What went wrong?

Response is 

```
<!DOCTYPE html>
<html lang="en">
...
</html>
```

Instead of the actual installer

## Which OS did you try on?

- [x] Mac
- [ ] Windows
- [ ] Linux

## What type of computer (i.e. laptop, desktop, Raspberry Pi)?

- [x] Laptop or Desktop (amd64 / x86-64)
- [ ] Raspberry Pi (ARM-64)
- [ ] Other (please specify, if you know)

I feel silly submitting this bug, but it seems like I am missing something to get the curl command to return the installer rather than the HTML from the website.

**Comment by ryanburnette** [comment]
Just curl the installer and post the entire contents of the response you're getting.

```bash
curl https://webinstall.dev/webi
```

**Comment by wburningham** [comment]
```| → curl https://webinstall.dev/webi
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Redirecting</title>
</head>
<body>
<pre>Redirecting to <a href="/webi/">/webi/</a></pre>
</body>
</html>```

**Comment by wburningham** [comment]
Running `curl -L https://webinstall.dev/webi` or `curl https://webinstall.dev/webi/` returns the full HTML from the website.

**Comment by wburningham** [comment]
It seems to be something with my work computer. I ran it on a personal computer and it works fine. I also ran it inside a docker container running on my work computer and it worked fine. What is the logic on your server that determines whether or not to return the installer or the HTML?

**Comment by coolaj86** [comment]
Are you running on Windows? Try `curl.exe` instead of `curl`.

It's based on the User-Agent. If the user agent says "curl" or "wget" or "PowerShell" it returns the script. Otherwise it returns the HTML.

You may have a proxy at work that pre-caches the results of the html.

Generally it's a bad practice to do the user-agent sniffing the way that I'm doing, but I figured that there's really only 3 user agents that qualify for the script.

I guess it would be good to add some failsafe URLs:

- https://webinstall.dev/sh/*
- https://webinstall.dev/pwsh/*
- https://webinstall.dev/README/*

And the scripts should always refer to those rather than the default.

**Comment by coolaj86** [comment]
You could try:

```bash
curl -A "curl wget bash linux x64" https://webinstall.dev/webi?_cachebust=$(date '+%s')
```

**Comment by coolaj86** [comment]
(closing just because this is a one-off problem, but I still intend to address it)
