### ISSUE TITLE
[Bug] Fish is listed but does not install

### ISSUE THREAD

**Issue by cawoodm** [webinstall/webi-installers#294]
## What were you trying to install (or what else went wrong)?

https://webinstall.dev/fish/ says installation in Linux should work but it doesn't.

## What exactly did you do?

`curl -sS https://webinstall.dev/fish | bash`

## What went wrong?

```
Thanks for using webi to install 'fish@stable' on 'Linux/x86_64'.
Have a problem? Experience a bug? Please let us know:
        https://github.com/webinstall/packages/issues

No fish installer for Linux yet. Try this instead:
    sudo apt install -y fish
```

## Which OS did you try on?

- [ ] Mac
- [ ] Windows
- [X ] Linux

## What type of computer (i.e. laptop, desktop, Raspberry Pi)?

- [X ] Laptop or Desktop (amd64 / x86-64)
- [ ] Raspberry Pi (ARM-64)
- [ ] Other (please specify, if you know)

**Comment by cawoodm** [comment]
OK, then you might want to remove the Linux button.

**Comment by cawoodm** [comment]
It must be possible to say if yum exists then do yum install … if apt then apt. I mean I just ran off and ran 3 lunux commands and fish was installed.

**Comment by coolaj86** [comment]
Yes, but the point of Webi is that is safe, uncomplicated, and cross platform:

- modern, static builds
- no sudo
- installs to ~/.local

There are a very small number of exceptions to that - such as WSL and pyenv, but only because they’re so incredibly necessary for the average developer and so easy to get wrong.

P.S. as stated above Mac and Linux aren’t separate, so I’d have to add some meta info and create a way to remove the Linux button.
