### ISSUE TITLE
[Bug] PowerShell installation is broken

### ISSUE THREAD

**Issue by ajeetdsouza** [webinstall/webi-installers#299]
## What were you trying to install (or what else went wrong)?

Tried with `bat`, `rg`, `zoxide`. They all seem to be broken.

## What exactly did you do?

```pwsh
curl.exe -A "MS" https://webinstall.dev/rg | powershell
```

## What went wrong?

```
& : The term 'C:\Users\ajeet\.local\bin\webi-pwsh.ps1' is not recognized as the name of a cmdlet, function, script file, or
operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:3
+ & "$Env:USERPROFILE\.local\bin\webi-pwsh.ps1" "bat"
+   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\Users\ajeet\.local\bin\webi-pwsh.ps1:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
```

## Which OS did you try on?

- [ ] Mac
- [x] Windows
- [ ] Linux

## What type of computer (i.e. laptop, desktop, Raspberry Pi)?

- [x] Laptop or Desktop (amd64 / x86-64)
- [ ] Raspberry Pi (ARM-64)
- [ ] Other (please specify, if you know)

**Comment by coolaj86** [comment]
Will you post the full output?

This is the file that downloads from the initial curl:
https://github.com/webinstall/webi-installers/blob/main/_webi/bootstrap.ps1

Which immediately downloads the webi script:
https://webinstall.dev/packages/_webi/webi-pwsh.ps1

Which then downloads the specific installer.

It seems as though somehow curl is failing to download that file - or at least powershell is reporting that ot doesn’t exist.

I haven’t made any changes to the Windows scripts since they were last tested, but my Windows VM is borked and needs to be reinstalled so I can’t easily test this right now.

**Comment by ajeetdsouza** [comment]
I don't know why or how, but it appears to be working for me again. When I posted this issue, I had tested it multiple times with different applications and I was getting the same error every time. If this is happening with no changes on the server end, it may still be worth investigating why installation is flaky.

Perhaps @beb- might have the error output?

**Comment by coolaj86** [comment]
Closing this but leaving https://github.com/webinstall/webi-installers/issues/300 open. They seem to be the same issue.

I’m guessing a restart of either the terminal or computer fixes it. Needs more investigation to know why.

**Comment by coolaj86** [comment]
SOLVED!

Webi is intentionally designed to be secure. DO NOT "run as admin". Doing so will break `$Env:USERPROFILE`.

See <https://github.com/webinstall/webi-installers/issues/300#issuecomment-976332468>.
