### ISSUE TITLE
[Feature Request] don't inject envman if ~/.local/bin is already in the path

### ISSUE THREAD

**Issue by adamcstephens** [webinstall/webi-installers#322]
Hello. I have ~/.local/bin in my PATH already, but webinstall is injecting the envman inclusion anyway. It took me some digging to figure out this came from webinstall, as the message `# Generated for envman. Do not edit.` does not indicate the true source.

Would it be possible to check the existing PATH and **not** inject these lines?

**Comment by coolaj86** [comment]
Because there's no standard way to define or check for `PATH` updates - especially across shells and operating systems - pathman/envman is really the only sane way to go.

HOWEVER, I think it would be very reasonable to always include a `Files` section in the README listing any files on the system that may be modified, and always include `~/.config/envman/PATH.env`.

What do you think about that?

**Comment by coolaj86** [comment]
P.S. What problem were you experiencing that made it important to not have `~/.local/bin` in your PATH a second time? Generally this is benign.

**Comment by adamcstephens** [comment]
webinstall isn’t just adding ~/.local/bin a second time, though I’d ask why bother modifying user’s config files to do so. webinstall is adding an entire new include location that could have arbitrary PATHs added to it. I manage my config files in git, so it was quite obvious to me that this was added. The problem is it’s an unnecessary addition, and I’d either have to manage this new file or blindly trust whatever PATHs are in it.

I’m excited about this project. I like the idea of a single installer script that can install multiple different tools, given that this is how projects are shipping now.

I’d be happy to prepare a PR if you’re ok with this request.

**Comment by coolaj86** [comment]
Yeah, that would be great.

I may be better to put that logic into pathman as an option rather than webi, but you investigate and let me know what you think is the best route.

I expect to continue to support bash and fish on all OSes (including Windows), and powershell and cmd.exe on Windows (bonus if powershell works on *nix too, but not a goal).

And I definitely want to be more clear on the installers as to what files are modified, but that’s another topic perhaps.

**Comment by coolaj86** [comment]
Many platform-programs, such as node, go, and even should-be stand-alone apps, such as gpg need to have multiple of their own PATH updates, such as `~/.local/opt/go/bin/` and `~/go/bin/`.

The idea behind envman / pathman is to create a standard machine-readable location for cross-shell changes - kinda like `git config x.y z`

**Comment by ajeetdsouza** [comment]
@coolaj86 

I've outlined this in previous discussions as well, but (like a lot of users) I maintain my dotfiles using git, and I hate when tools change things around without asking me. To me, the best tool would be a tool that:

1. Installs the binary to `$LOCATION`
2. Checks that `$LOCATION` is present in `$PATH`
3. If not, _asks_ whether it can edit my config files to add it automatically (it should list the files that would be edited)
4. The section added to my config file should mention that it was created by webi

I'm not very happy with the fact that that the `webi`/`envman`/`pathman` binaries are installed on my system when all I wanted was to install 1 application. If you want to promote webi and install it by default, that's quite understandable, but I feel like the rest can be done without installing more stuff.

**Comment by adamcstephens** [comment]
I completely agree with @ajeetdsouza, and it was their app zoxide which brought me here.

**Comment by coolaj86** [comment]
Asking is a problem for two reasons:

1. `curl | bash` steals the file descriptor of the tty and it's _really_ hard to find a cross-platform, cross-shell way to get it back
2. By default, webi should do the thing that Just Works™

That said, I'm very open to adding an option `--no-path-updates` and `--no-webi`.

`pathman` (which was intended to be renamed envman) has been a necessary evil. However, I think it may be possible to do what it needs to do for bash in webi. That said, I want to stick with philosophy of `pathman` in producing machine-readable changes.

In some future, webi should be able to uninstall go and remove `~/.local/opt/gobin/` from the PATH when `go` is uninstalled.

**Comment by adamcstephens** [comment]
> I think adding a by webi via pathman to the comment would be great.

It looks like this will require modifying pathman, since that is where the existing comment is being generated.

https://git.rootprojects.org/root/pathman/src/commit/2c283a28649a692fea764894415cfa6b74fe2f5b/envpath/manager.go#L185
https://git.rootprojects.org/root/pathman/src/commit/2c283a28649a692fea764894415cfa6b74fe2f5b/envpath/manager.go#L216

Combining a more appropriate comment with outputting that this is happening would seem an appropriate first step for me. The latter could be done by not redirecting the pathman output to a file:

https://github.com/webinstall/webi-installers/blob/2d68b08174ff6d37b5b3f42e51d5e9802d96e2a0/_webi/template.sh#L245

I've looked through the code, but will not be submitting a PR after a further review. This issue is not an appropriate forum for a difference of vision, but if you're interested in a more detailed set of feedback let me know.

**Comment by coolaj86** [comment]
> I've looked through the code, but will not be submitting a PR after a further review.

Are you talking about the Go code, the Bash, or the Node that templates that Bash?

The Go code should be pretty straightforward to add a flag to update the comment. It would also be nice to change the output options.

The bash code has gotten grosser over time. Just lots of edge cases and... it's bash.

Now that the use cases have been explored, however, I think that there's a fair amount of code that can be eliminated and, ultimately, I think it could work to move toward mostly pre-generated installer scripts.

> if you're interested in a more detailed set of feedback let me know

Let's do it: https://github.com/webinstall/webi-installers/discussions/329

**Comment by ajeetdsouza** [comment]
> `curl | bash` steals the file descriptor of the tty and it's really hard to find a cross-platform, cross-shell way to get it back

I see. A separate `curl` followed by `bash` would have worked (or `bash -c`), but that would not be as elegant or memorable, I suppose.

> By default, webi should do the thing that Just Works™ without additional user interaction

I agree that we should do what works by default, but if it were possible, I would have preferred a prompt for "Would you like to add these paths automatically to your .bashrc? [Y/n]", where the _default_ answer is yes.

> However, I think it may be possible to do what it needs to done for webi just using bash at this point. That said, I want to stick with the philosophy of in producing machine-readable changes.

I'm not sure how pathman would help here.

Suppose I have two programs (say X and Y) installed to `~/.local/bin`. Now I uninstall X. Does pathman remember that Y is still installed there, so it should not remove the path?

Even if it does do that, suppose I have started relying on `~/.local/bin` being in my path. A lot of utilities install themselves there, this is a pretty common path to use. Now I install Y as well, and webi removes the path. All of a sudden, I can't access any of the programs in my directory, causing confusion.

This is why I suggest that users should be allowed to maintain their PATHs in their own config files. We could automatically add a line to the user's config file, but after that the user should be allowed to manage the paths themselves. Moreover, this can/should be achieved inside bash / powershell itself, without the need for pathman. pathman does seem a bit overkill here.

> That said, I'm very open to adding an option --no-path-updates and --no-webi.

This sounds great.

> I think adding a by webi via pathman to the comment would be great.

Agreed.

**Comment by ajeetdsouza** [comment]
@coolaj86 here's another issue I got regarding this: https://github.com/ajeetdsouza/zoxide/issues/318

This has also been mentioned in a discussion: https://github.com/webinstall/webi-installers/discussions/348

For automated installers, a major problem that users have is trust. While I appreciate the goal of never using `sudo`, I think that the obvious next step is to not automatically add extra binaries that the user didn't ask for, and to avoid modifying user configuration files. If I may suggest a course of action:

- `webi` should not be included at all. If users use `webi` enough, they'll install it themselves.
- `pathman` should be an opt-in thing, rather than something to explicitly _disable_ with a command-line flag.

I'd appreciate it if you could tell me if this is a planned feature for Webi v2, because all 3 of these users have come from zoxide, which lists `webi` as the primary mode of install.

**Comment by adamcstephens** [comment]
Personally I reverted to the old `zoxide` install script and [patched it to work](https://github.com/adamcstephens/dotfiles/blob/1a6ed84ca71ddff857f01541adb37677737d9157/bin/install-zoxide.sh), allowing me to eliminate `webi` from my setup. As long as these issues exist, I have no interest in webi installer

**Comment by ajeetdsouza** [comment]
@adamcstephens I just re-read this discussion: https://github.com/webinstall/webi-installers/discussions/329

It doesn't seem like @coolaj86 is going to budge on the issue of path updates. This is rather unfortunate, as I think a major part of package management revolves around trust, and scripts that perform unnecessary modifications to one's system immediately appear untrustworthy.

If I'm using an install script, I usually always skim through the source. I would immediately be uncomfortable with an installer that had code to download more binaries than I asked for or to modify my config files, _even if it occurred in an if-else block that wouldn't actually execute on my system_.

I thought this was just me (I pointed out this issue months ago in https://github.com/webinstall/webi-installers/issues/255), but now that I see that others are uncomfortable with it too, I cannot keep asking them to use webi. Even if webi v2 ever gets built, I don't think I want to ask users to use `--no-path-updates` and `--no-webi` to _disable_ all the unwanted stuff that comes with the installer.

---

@coolaj86 I hope you take this feedback constructively, but I'll be moving away from webi. The final nail in the coffin for me has been the development velocity here. My initial PR (https://github.com/webinstall/webi-installers/pull/223) took 2 months of follow-up before it got merged. [Here's](https://git.rootprojects.org/root/pathman/issues/5) a 2-week old issue that hasn't gotten a response yet.

I fully understand that you're building a free project in your spare time, but zoxide has been downloaded from GitHub around 16000 times since I made webi the "preferred" mode of installation. I imagine a sizeable fraction of these downloads were from here. Switching to webi was supposed to make things easier for me, but every time the installer breaks, it takes me more time to follow up on the issue here than it would have taken me to fix it myself.

---

Lastly, I really do hope that this project succeeds! I think a tool that consolidates the hundreds of `curl | bash` installers out there is long overdue. For anyone reading, do check out the rest of [Root projects](https://therootcompany.com/). They have some pretty cool ideas.

**Comment by coolaj86** [comment]
Fixed in #505, just for you @adamcstephens! 😘
