### ISSUE TITLE
update Windows pathman to enable console output

### ISSUE THREAD

**Issue by coolaj86** [webinstall/webi-installers#34]
Pathman's `release.js` needs to be updated to select pathman.debug.exe for windows, maybe, so that pathman will output text in Terminal.

Or in some way shape or form we need to choose between GUI-enabled and Terminal-enabled pathman.

Also, not sure what the difference between these two might be or which should be added:

- `.local\bin`
- `%USERPROFILE%\.local\bin`

Also, using quotes seem to mess up the pathnames.

Also, pathman sometimes seems to cause hangs (potentially after modifying the registry?) but then continues when 'enter' is pressed.

cc/ @jkunkee Thoughts?

**Comment by jkunkee** [comment]
`PATH` is all absolute paths, so `%USERPROFILE%\.local\bin` will work when the current folder is not `%USERPROFILE%`.

Quotes in paths are not needed because they are semicolon-delimited and not space-delimited. The registry API should take a raw string, again with no need for quotes inside the string. Is that where you're seeing quote issues?

The interplay between console apps and conhost.exe is a bit messy for aggregated historical reasons. Pressing enter probably flushes some buffer on a pipe that was being waited on; closing the pipe (probably `stdio` or similar) should work just as well.

**Comment by jkunkee** [comment]
Outputting text to the terminal should be an application choice, so whether the non-`.debug.` pathman does so should be under your control.

It is possible to have the GUI exe present a CLI--I've seen it done before--but a common design pattern is `pathman.exe` with `pathmanui.exe`.

**Comment by solderjs** [comment]
@jkunkee Any update on using a function for the output?

**Comment by jkunkee** [comment]
Haven't had a chance to pursue it further, no. The behavior of `&` in PowerShell in tandem with piping puzzled me then; I'll probably switch to Invoke-Command or similar.

**Comment by solderjs** [comment]
@jkunkee Do you have time that we could work on this tomorrow (Saturday)?

**Comment by coolaj86** [comment]
closing with with label `someday`
