### ISSUE TITLE
webi --help – is going to install package --help

### ISSUE THREAD

**Issue by kuvaldini** [webinstall/webi-installers#363]
```
>>> webi --help
curl: (22) The requested URL returned error: 404
error fetching 'https://webinstall.dev/api/installers/--help.sh?formats=tar,exe,zip,xz,git,dmg,pkg'
```

This flag works for 99% CLI utilities, let's get it work as usual.

**Comment by coolaj86** [comment]
@kuvaldini How's your bash and powershell?

I'd accept PRs that modify `_webi/bootstrap.sh` or `_webi/webi-pwsh.ps1` to respond to:
- -h
- --help
- help
- install
- -i
- --install

`--install` would be a no-op, but useful since some people (including myself) type it out from muscle memory by mistake sometimes.

`--help` should probably list out usage and common files that are edited. Something like this:

```txt
Usage:
    webi <package>[@version] ...

Example:
    webi node@lts golang@1.16 rg@latest pyenv

Files:
    Webi tries to follow the filesystem standards and touch as little of your system as possible. These are the files that webi is likely to add or modify:

Your shell's "run commands" file, which is one of:
    ~/.profile
    ~/.bashrc
    ~/.zsh
    ~/.config/fish/config.fish

The shared PATH environment file:
    ~/.config/envman/PATH.env

The package's installation location, "man" (reader's manual), and configuration files:
    ~/.local/opt/<package>/bin/<package>
    ~/.local/opt/<package>/share/man/man1/<package>.1
    ~/.local/bin/<package>
    ~/.local/share/man/man1/<package>.1
    ~/.config/<package>/<configfile>
```

## Where to make the change?

See
- https://github.com/webinstall/webi-installers/blob/1c757ef9b113abf86f0c7aab18db8162cc8852b6/_webi/bootstrap.sh#L148
- https://github.com/webinstall/webi-installers/blob/main/_webi/webi-pwsh.ps1
