### ISSUE TITLE
[Bug] vim-go: Go 1.18 drops support for `go get` (replaced by `go install`?)

### ISSUE THREAD

**Issue by coolaj86** [webinstall/webi-installers#441]
Originally we used `go get` because `go install` wouldn't work with go modules.

Now `go get` won't work _with_ go modules and `go install` does.

I think the solution is to replace `go get` with `go install` in https://github.com/webinstall/webi-installers/blob/main/vim-go/install.sh

# Workaround

```bash
webi vim-go

vim main.go
```

```vim
:GoInstallBinaries
```

**Comment by saikmusunuri** [comment]
Hey @coolaj86, can you please assign it to me. I would like to contribute to this. Thanks!

**Comment by saikmusunuri** [comment]
Hey @coolaj86, any update on this?

**Comment by coolaj86** [comment]
@saikmusunuri Please do.

**Comment by saikmusunuri** [comment]
Thanks! I will start working on it very soon.

**Comment by saikmusunuri** [comment]
Hey @coolaj86, please review the PR.  Thanks!

**Comment by saikmusunuri** [comment]
Hey @coolaj86, I once again request you to review the PR. Thanks!

**Comment by candrewlee14** [comment]
Due to both inactivity & pain points when implementing my nvim package #437, I decided to write my own cross-platform package manager called [webman](https://github.com/candrewlee14/webman), inspired by webi. It handles package installation, removal, and switching all with a single yaml file per package.

**Comment by coolaj86** [comment]
Closing because this was fixed and merged.
