### ISSUE TITLE
Proposal: Do NOT update by default

### ISSUE THREAD

**Issue by coolaj86** [webinstall/webi-installers#549]
See <https://twitter.com/_webinstall/status/1614505783470993408>.

We're considering changing the default behavior of to make scripting with webi more convenient (reducing # of web requests):

Current: \
`webi thing` will INSTALL or UPDATE `thing`

Proposed: \
`exit 0` if `thing` is in `PATH`

Only `webi thing@latest` will update `thing`.

This would NOT be a breaking change.
(in fact, it will probably reduce breakage in scripts)

It does raise the question of what the behavior of `webi@v1' should be. Update to latest v1?

Either way there needs to be some sort of "no update" mechanism.

Thoughts?

cc/ @ryanburnette @y0rune @jojobyte

**Comment by y0rune** [comment]
Hello!
Currently in the systems like Gentoo, CentOS the default behavior is updating (or rebuilding when the package is installed). So I think the users use it likes in that systems, so that behavior is excepted. The your idea is correct to user when the user see that information or the user can decide what is should be done. Example:
Steps:
1. `webi fzf` - it installs the fzf
2. `webi fzf` - it will check the path when it will find the user will get the information: `Would you like to update that package? [Y/N]`.

I think that way is correct to reduce the web request. 

If you have another consider or question about my idea please ask ;)

--
Thank you!
Marcin

**Comment by coolaj86** [comment]
Thanks to feedback in DMs and here GitHub, we're NOT making this change.

What we may do instead is add some sort of `--no-update` flag.
