### ISSUE TITLE
suggestion: use pre-compiled brew bottles 

### ISSUE THREAD

**Issue by tnxz** [webinstall/webi-installers#550]
So there is this project [oras](https://github.com/oras-project/oras) which basically push (upload) and pull (download) things to and from an OCI Registry.

Homebrew stores their bottles in a [registry](https://github.com/orgs/Homebrew/packages) which we can pull via oras.

We can leverage the [brew api](https://formulae.brew.sh/docs/api) to obtain the bottle link and add it to `~/.local/bin`.

As the registry is a public registry it doesn't require authentication to pull packages.

**Comment by coolaj86** [comment]
I actually considered this very early on and even had a prototype, however there are a few problems:

The most important is the philosophical, but I'll start with the technical:

1. `brew` precompiles binaries to look for shared libraries in a specific absolute paths `/usr/local/...`. This means that if they are relocated to `~/.local/opt/...` they simply won't run. If we install them into `/usr/local`, then
   - A) that requires `sudo`
   - and B) it will have the same problems that brew already has with library and permission conflicts.
2. More importantly, Webi is to help modern developers use simpler, modern tools more easily. It's a lot more work to get older programs to compile and install correctly

# And we do offer [`brew`](https://webinstall.dev/brew)!

However, we do offer <https://webinstall.dev/brew>, which actually does solve A) and B) and, since it requires a full compiler toolchain and many things have to recompile to support the location of `~/.local/opt/...` anyway, the initial 500mb download is isn't as big of a deal.

# Bring your Suggestions!

If something is keeping you stuck on `brew`, add a request for it.

Some things can't be installed with `webi` (because of point 1), and some things don't fit in with the philosophy of webi's focus on modern tools, but I don't think I've rejected a complete PR yet (and there are a few outstanding PRs that still need help from someone who uses the tool).

**Comment by tnxz** [comment]
`brew` size wasn't an issue as i use `HOMEBREW_INSTALL_FROM_API`, relocating brew to `~/.local/opt` breaks `casks`. Anyways looking farward for what this tool entails ahead.
