### ISSUE TITLE
Why not install to /usr/local/bin?

### ISSUE THREAD

**Issue by cekvenich2** [webinstall/webi-installers#553]
golang, ruby, etc all do this.
Pyenv does it via env variable.

Right now I have to install in ~ and them mv.

**Comment by coolaj86** [comment]
@cekvenich2 What are the problems you're trying to solve?

Did you follow the instructions at the end to `source ~/.config/envman/PATH.env`?

Back in the old days, it was common to install things into `/usr` and `/usr/local` for various reasons that don't apply today. In fact, the bugs and inconsistencies that result from putting user-level tools into system directories is a big part of what `webi` was built to solve - for example, `brew`, `go`, and `node` will all corrupt each others' permissions depending on what order you install them in if you use `.pkg` files or `sudo`.

Webi installs locally so that you _don't_ have permission or PATH errors.

So what's the issue that you're trying to find a workaround for?

**Comment by cekvenich2** [comment]
I have no problem installing running this, works great, love it. What I do after install is issue mv commands to move from ~./ to user/local. It seems like I should not need to do that.
Of course if I want to run it from ~ without touching, great. But I'd like it under /usr/local and now I have to add 4-5 lines of bash to to that.

**Comment by coolaj86** [comment]
Every time you install something you get a message like this:

```text
TO FINISH: copy, paste & run the following command:

        source ~/.config/envman/PATH.env
        (newly opened terminal windows will update automatically)
```

That's all you have to do - either `source` or close the Terminal window and open a new one.

**Comment by spoelstraethan** [comment]
The reason i would prefer an option to install to /usr/local/ is that on macOS that is accessible to more users than just my own, and on ChromeOS in Developer Mode where there isn't really a package manager, the /usr/local path is the ONLY filesystem that is NOT mounted `+noexec` so using webi to install there fails because it can't execute files like `~/.local/bin/webi`.
