### ISSUE TITLE
problem with Webi installer on Windows

### ISSUE THREAD

**Issue by sorenrichenberg** [webinstall/webi-installers#799]
I'm trying to install webi on windows using powershell, and I'm getting a big red error. I attached a text file with my terminal output.
It seems like the problem could be related to the space in my windows username, since the error term cuts off the file path after my first name.

![image](https://github.com/webinstall/webi-installers/assets/37592101/32a4fe99-b206-4841-af7d-6daa2f622648)

[Windows PowerShell.txt](https://github.com/webinstall/webi-installers/files/13882296/Windows.PowerShell.txt)

**Comment by coolaj86** [comment]
Yes, I'm going to say it probably is the space in your Windows username.

My understanding is that spaces are actually not allowed in Windows usernames anymore (it will truncate or use underscores with recent installs - precisely due to command line issues).

How long ago did you create that user on your computer?

And now I'm confused because I could have sworn that PowerShell variable expansion kept strings together.

I'll have something for you to test in a few minutes.

**Comment by sorenrichenberg** [comment]
I created my user account on July 20th 2023 with a fresh install of Windows 11 Education. It's a non-microsoft.com local account. Usually I tell Windows that my full name is something like "srichenberg," and then change it later on, but I forgot about it for this install.

**Comment by coolaj86** [comment]
@sorenrichenberg Go ahead and give it a try now. It looks like there were only 3 places where it should have been quoted but wasn't.

**Comment by sorenrichenberg** [comment]
@coolaj86 I just tried it again and got the same error message.

**Comment by coolaj86** [comment]
I was able to create a user with spaces on a Windows system that I have.

Apparently they've stepped back the "no spaces" in a big way - or maybe it just depends on which dialog box you use to create the user.

I've found a workaround. I'm digging a bit to see if I can find an actual _fix_.

**Comment by coolaj86** [comment]
Okay, I've deployed the fix and tested that it works.

I'll close this out, but please reopen if you have any trouble.
