### ISSUE TITLE
Linux Postgres version is out of date (v10 vs v16)

### ISSUE THREAD

**Issue by spa5k** [webinstall/webi-installers#823]
## What were you trying to install (or what else went wrong)?
Postgres

## What exactly did you do?
Installed postgres, found out that it installs v10 for stable, and higest possible version is 12.3 from here - https://webinstall.dev/api/releases/postgres

## What went wrong?
It should be v16.2

## Which OS did you try on?

- [ ] Mac
- [ ] Windows
- [x] Linux

## What type of computer (i.e. laptop, desktop, Raspberry Pi)?

- [x] Laptop or Desktop (amd64 / x86-64)
- [ ] Raspberry Pi (ARM-64)
- [ ] Other (please specify, if you know)

**Comment by coolaj86** [comment]
The problem here is that EnterpriseDB (the PostgreSQL company) stopped supporting Linux around v10.x.

- https://www.enterprisedb.com/downloads/postgres-postgresql-downloads
- https://www.postgresql.org/download/linux/#generic

It's now up to maintainers to roll their own packages, and I don't have the resources to do that.

There's probably a way to extract the binaries from the .deb or .rpm and they're _probably_ built in a way that they'll install on any Linux. However, dependency management may become an issue.

**Comment by coolaj86** [comment]
I'm open to finding a solution, but I need help - probably from someone who has built PostgreSQL binaries before.

**Comment by spa5k** [comment]
That is indeed a problem, I think we can just mark Postgres as deprecated for now.

**Comment by coolaj86** [comment]
Closing this out for now.

I think my fix is going to be to use "polite sudo" and install from the package manager, but with a local data dir.

**Comment by coolaj86** [comment]
The time is at hand:
- https://github.com/bnnanet/postgresql-releases/releases/tag/REL_17_0
- https://github.com/webinstall/webi-installers/pull/908

I'll officially be maintaining `postgres` and `psql` builds as part of my work with bnna.net.

The fresh builds are at https://beta.webinstall.dev/pg and https://beta.webinstall.dev/psql \
(they're actively being worked on so they if there's an error, just try again in a few minutes)

## Backstory

I've been anxiously awaiting for Postgres 17 to release since they finally added standard TLS support (including SNI and ALPN). And despite keeping a keen eye on the release, I missed that it actually dropped two weeks ago.

Anyway, since I know it may not come to Debian and Ubuntu for a few years, and possibly not to Alpine for several months, and since I've had enough discussion on the mailing list to know that the core team is simply not interested in standalone builds (but getting enough direction to point me in the right direction), I finally sunk a day into figuring out how to get it to compile in a way that's acceptable.

The solution isn't to compile statically (the core team has given that a hard pass to everyone who has asked), but rather to bundle dynamic libraries with modified rpath so that they can be found from the project's `./lib/` folder.

I'm going to try to finish the process for the macOS build before this officially goes live, but I will have complete scripts that I'll be running regularly as new postgres releases come out.

I believe I've found the right balance of things that are trivial and should just be bundled (zlib, readline), things that shouldn't be bundled (openssl, tzdata), and things that can be optional (llvm for jit query planner optimization).
