### ISSUE TITLE
[verified not-affected] xz backdoor vulnerability

### ISSUE THREAD

**Issue by 3f6a** [webinstall/webi-installers#828]
`xz` is [compromised](https://www.openwall.com/lists/oss-security/2024/03/29/4). I'm not sure if the version provided by `webi` is affected or not, so I just wanted to point this out (I could not find any issue about it).

**Comment by coolaj86** [comment]
Yikes! That's incredibly bad!

The good news is that, since xz is in the public domain, and there is no official builds, nor an official maintainer, the webi version is a fork of what was the most popular repo back at v5.2.5 and is statically linked:

https://github.com/therootcompany/xz-static/releases

**Comment by coolaj86** [comment]
And thank you very, very much for the report.

**Comment by coolaj86** [comment]
`xz` is only used by Webi in the form of `unxz` for decompressing package files from GitHub Releases and the like.

Webi doesn't do any compiling of libraries or dependency management.
