### ISSUE TITLE
lsd installer 500 code

### ISSUE THREAD

**Issue by skovranek** [webinstall/webi-installers#876]
```sh
~ $ curl -sS https://webi.sh/lsd | sh


>>> Welcome to Webi! - modern tools, instant installs.  <<<
    We expect your experience to be absolutely perfect!

    Success? Star it!   https://github.com/webinstall/webi-installers
    Problem? Report it: https://github.com/webinstall/webi-installers/issues
                        (your system is Darwin/arm64 with libc & curl)

Bootstrapping Webi
    Found ~/.local/bin/webi
    Running ~/.local/bin/webi lsd@stable

curl: (56) The requested URL returned error: 500
error fetching 'https://webi.sh/api/installers/lsd@stable.sh?formats=tar,exe,zip,xz,git,dmg,pkg'
~ $
```

**Comment by skovranek** [comment]
resolved, thank you

**Comment by coolaj86** [comment]
I had some release linting that throws an error that was supposed to get caught and logged as a warning whenever release formats change in a way that cause target detection to fail (os, arch, platform, package format, deliver method).

Well, it looks like a stray file was uploaded (accidentally, I assume) to the latest GitHub Releases for `lsd` (<https://github.com/lsd-rs/lsd/issues/1090>), and it turns out that my linter wasn't catching and logging, it was letting the error bubble.

Fixed in https://github.com/webinstall/webi-installers/pull/877
